# Generated by Django 5.1 on 2024-09-21 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home_App', '0004_alter_customer_state_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
